language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install ."
  - pip install -r devenv-requirements.txt
script:
  - flake8 nredarwin
  - flake8 tests
  - python setup.py test
