# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: devenv-requirements.txt 
      - lint:
          name: Lint
          command: flake8 nredarwin && flake8 tests
      - test:
          name: Run tests
          command: coverage run --source=nredarwin/ --omit=nredarwin/cli.py -m unittest discover
 

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
